### ISSUE TITLE
007 - Agent Under Fire 60 FPS patch malformed

### ISSUE THREAD

**Issue by JayYardley** [icup321/XboxGraphicalPatches#7]
Location: **60 FPS Patches /** 007 - Agent Under Fire (60 FPS Patch).ips

The data is as follows:
50415443 48128A9B 00010145 4F46

50415443 48 = "PATCH"
**128A9B = Offset lcoation**
0001 = Size
01 = Data
45 4F46 = "EOF"

The offset "**128A9B**" does not exist in the NTSC xbe file.

**Comment by jao12345** [comment]
You have to patch bond.xbe

**Comment by JayYardley** [comment]
> You have to patch bond.xbe

Brilliant thanks for that, of course!
